name: "Check Git Status"
description: "Fail the workflow or git push based if git status is not clean."
inputs:
  fail-if-not-clean:
    description: "Fail the workflow if git status is not clean."
    required: true
    default: true
  push-if-not-clean:
    description: "Commit the changes and push them to the origin if git status is not clean."
    required: true
    default: false
  github-token:
    description: "GitHub token to use when pushing new changes."
    required: true
    default: ${{ github.token }}
outputs:
  status:
    description: "Is git status clean or dirty?"
    value: ${{ steps.git-status.outputs.status }}
runs:
  using: "composite"
  steps:
    - id: git-status
      name: git status
      shell: bash
      run: |
        if git rev-parse --verify HEAD >/dev/null 2>&1
        then
          against=HEAD
        else
          # Initial commit: diff against an empty tree object
          against=$(git hash-object -t tree /dev/null)
        fi
        git add -AN
        if test $(git diff --name-only $against | wc -l) != 0
        then
          echo "::set-output name=status::dirty"
        else
          echo "::set-output name=status::clean"
        fi

    - id: exit-1
      name: exit 1
      if: ${{ steps.git-status.outputs.status == 'dirty' && (inputs.fail-if-not-clean == 'true' || (inputs.push-if-not-clean == 'true' && github.event_name != 'pull_request')) }}
      shell: bash
      run: exit 1

    - id: git-config
      name: git config
      if: ${{ steps.git-status.outputs.status == 'dirty' && inputs.push-if-not-clean == 'true' && github.event_name == 'pull_request' }}
      shell: bash
      run: |
        git config --global user.name `git log -n 1 --pretty=format:%an`
        git config --global user.email `git log -n 1 --pretty=format:%ae`

    - id: git-commit
      name: git commit
      if: ${{ steps.git-status.outputs.status == 'dirty' && inputs.push-if-not-clean == 'true' && github.event_name == 'pull_request' }}
      shell: bash
      run: |
        git commit -am 'Updated by GitHub Workflow Check Git Status Action'

    - id: git-push
      name: git push
      if: ${{ steps.git-status.outputs.status == 'dirty' && inputs.push-if-not-clean == 'true' && github.event_name == 'pull_request' }}
      shell: bash
      env:
        BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        GITHUB_TOKEN: ${{ github.token }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        git fetch --unshallow origin
        if [[ $GITHUB_TOKEN != $GH_TOKEN ]]
        then
          gh auth status
          gh api -H "Accept: application/vnd.github+json" /user
          gh auth setup-git
          OVERRIDE_LOGIN=$(gh api -H "Accept: application/vnd.github+json" /user -q '.login')
          OVERRIDE_REMOTE=$(git remote get-url origin --push | sed 's/^https:\/\//https:\/\/'"$OVERRIDE_LOGIN:$GH_TOKEN"'@/')
          echo "git push -f --set-upstream $OVERRIDE_REMOTE HEAD:refs/heads/$BRANCH_NAME"
          git push -f --set-upstream "$OVERRIDE_REMOTE" "HEAD:refs/heads/$BRANCH_NAME"
        else
          echo "git push -f --set-upstream origin HEAD:refs/heads/$BRANCH_NAME"
          git push -f --set-upstream origin "HEAD:refs/heads/$BRANCH_NAME"
        fi
branding:
  icon: "edit-3"
  color: "red"
