name: Debug

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  debug_information:
    name: Debug Information
    runs-on: ubuntu-latest

    steps:
      - name: Print contexts
        env:
          GITHUB: ${{ toJSON(github) }}
          JOB: ${{ toJSON(job) }}
          INPUTS: ${{ toJSON(inputs) }}
        run: |
          echo "::debug::github = $GITHUB"
          echo "::debug::job = $JOB"
          echo "::debug::inputs = $INPUTS"
