name: Dependabot

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dependabot-test:
    name: Dependabot
    if: ${{ !startsWith(github.head_ref, 'workflows/tests/') && github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
