name: Release

on:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
      prerelease:
        description: 'Prerelease'
        required: true
        default: false
        type: boolean
      skip-if-no-diff:
        description: 'Skip if no diff'
        required: true
        default: false
        type: boolean
      diff-targets:
        description: 'Diff Targets'
        required: false
        default: '{action.yml,README.md}'
        type: string
      dry-run:
        description: 'Dry run'
        required: true
        default: false
        type: boolean

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    name: Release
    needs: [test]
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: get-github-app-token
        with:
          app-id: ${{ secrets.ACCEPT_TO_SHIP_BOT_APP_ID }}
          private-key: ${{ secrets.ACCEPT_TO_SHIP_BOT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0

      - id: release
        uses: CatChen/node-package-release-action@v2
        with:
          release-type: ${{ inputs.release-type || 'patch' }}
          prerelease: ${{ inputs.prerelease || false }}
          update-shorthand-release: true
          dry-run: ${{ inputs.dry-run || false }}
          skip-if-no-diff: ${{ inputs.skip-if-no-diff || github.event_name != 'workflow_dispatch' }}
          diff-targets: ${{ inputs.diff-targets || '{action.yml,README.md}' }}
          github-token: ${{ steps.get-github-app-token.outputs.token }}
