name: Release

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    name: Release
    needs: [test]
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - uses: CatChen/accept-to-ship-action@v0.1.2
        with:
          release-type: patch
