name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches:
      [main, "[0-9]+-[0-9]+-*", "workflows/tests/[0-9]+-[0-9]+-on-[a-fA-F0-9]+"]
  workflow_dispatch:

jobs:
  test_clean:
    name: Test Clean
    if: ${{ !startsWith(github.head_ref, 'workflows/tests/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: CatChen/check-git-status-action@v0.1.3
        id: test-action

      - name: Verify outputs
        env:
          TEST_ACTION_OUTPUT: ${{ steps.test-action.outputs.status }}
        run: |
          if [[ $TEST_ACTION_OUTPUT != "clean" ]]
          then
            exit 1;
          fi

  test_dirty_failure:
    name: Test Dirty Failure
    if: ${{ !startsWith(github.head_ref, 'workflows/tests/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make dirty
        run: |
          touch `git rev-parse --verify HEAD`

      - uses: CatChen/check-git-status-action@v0.1.4
        id: test-action
        continue-on-error: true

      - name: Verify outputs
        env:
          TEST_ACTION_OUTPUT: ${{ steps.test-action.outputs.status }}
        run: |
          if [[ $TEST_ACTION_OUTPUT != "dirty" ]]
          then
            exit 1;
          fi

  test_dirty_push:
    name: Test Dirty Push
    if: ${{ !startsWith(github.head_ref, 'workflows/tests/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Config Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make commit
        env:
          SHA: ${{ github.sha }}
          RUN_NUMBER: ${{ github.run_number }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
          BASE_BRANCH_NAME: ${{ github.head_ref }}
        run: |
          echo "::debug::Run number is $RUN_NUMBER"
          echo "::debug::Run attempt is $RUN_ATTEMPT"
          echo "::debug::Base branch is $BASE_BRANCH_NAME"
          echo "::debug::Base commit is `git rev-parse --verify HEAD`"
          git checkout -b "workflows/tests/$RUN_NUMBER-$RUN_ATTEMPT-on-$SHA"
          echo "::debug::Test branch is `git branch --show-current`"
          touch $SHA
          git add -A
          git commit -am "Test commit for $SHA by $RUN_NUMBER-$RUN_ATTEMPT"
          echo "::debug::Test commit is `git rev-parse --verify HEAD`"

      - name: Git push
        env:
          SHA: ${{ github.sha }}
          RUN_NUMBER: ${{ github.run_number }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
          BASE_BRANCH_NAME: ${{ github.head_ref }}
        run: |
          git push -f --set-upstream origin "workflows/tests/$RUN_NUMBER-$RUN_ATTEMPT-on-$SHA"
          echo "::debug::Remote test branch is origin/`git branch --show-current`"

      - name: Open PR
        id: open-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.sha }}
          RUN_NUMBER: ${{ github.run_number }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
          BASE_BRANCH_NAME: ${{ github.head_ref }}
          BASE_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "::debug::Base PR number is $BASE_PR_NUMBER"
          gh pr create --base "$BASE_BRANCH_NAME" --title "Test PR for $SHA by $RUN_NUMBER-$RUN_ATTEMPT" --body "Generated by a workflow from #$BASE_PR_NUMBER"
          TEST_PR_NUMBER=`gh pr view | grep 'number:' | cut -f 2`
          echo "::set-output name=test-pr-number::$TEST_PR_NUMBER"
          echo "::debug::Test PR number is $TEST_PR_NUMBER"

      - name: Trigger Workflow
        env:
          GITHUB: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB" | gh workflow run debug.yml --json

      - name: Check PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sleep 10
          gh pr checks --watch
          echo "::debug::Test PR Checks\n\n`gh pr checks`"

      - name: Close PR
        if: always()
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.sha }}
          RUN_NUMBER: ${{ github.run_number }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
          BASE_BRANCH_NAME: ${{ github.head_ref }}
          TEST_PR_NUMBER: ${{ steps.open-pr.outputs.test-pr-number }}
        run: |
          if [ $BASE_BRANCH_NAME != '' ]
          then
            git checkout "$BASE_BRANCH_NAME"
            echo "::debug::Base branch is `git branch --show-current`"
          else
            git checkout "$SHA"
            echo "::debug::Base commit is `git rev-parse --verify HEAD`"
          fi
          gh pr close $TEST_PR_NUMBER -d -c "Finished testing $SHA by $RUN_NUMBER-$RUN_ATTEMPT. Closing PR."

      - name: Delete remote branch
        if: always()
        continue-on-error: true
        env:
          SHA: ${{ github.sha }}
          RUN_NUMBER: ${{ github.run_number }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
        run: |
          git push -d origin "workflows/tests/$RUN_NUMBER-$RUN_ATTEMPT-on-$SHA"
