name: Test

on:
  pull_request:
  push:
    branches: [main, "[0-9]+-[0-9]+-*"]
  workflow_dispatch:

jobs:
  test_clean:
    name: Test Clean
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: CatChen/check-git-status-action@v0.1.3
        id: test-action

      - name: Verify outputs
        env:
          TEST_ACTION_OUTPUT: ${{ steps.test-action.outputs.status }}
        run: |
          if [[ $TEST_ACTION_OUTPUT != "clean" ]]
          then
            exit 1;
          fi

  test_dirty_failure:
    name: Test Dirty Failure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make dirty
        run: |
          touch `git rev-parse --verify HEAD`

      - uses: CatChen/check-git-status-action@v0.1.3
        id: test-action
        continue-on-error: true

      - name: Verify outputs
        env:
          TEST_ACTION_OUTPUT: ${{ steps.test-action.outputs.status }}
        run: |
          if [[ $TEST_ACTION_OUTPUT != "dirty" ]]
          then
            exit 1;
          fi
