name: Test

on:
  pull_request:
  push:
    branches: [main, "[0-9]+-[0-9]+-*"]
  workflow_dispatch:

jobs:
  test_clean:
    name: Test Clean
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: CatChen/check-git-status-action@v0.1.2
