name: Test

on:
  pull_request:
  push:
    branches: [main, "[0-9]+-[0-9]+-*"]
  workflow_dispatch:

jobs:
  test_clean:
    name: Test Clean
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: CatChen/check-git-status-action@v0.1.3
        id: test-action

      - name: Verify outputs
        env:
          TEST_ACTION_OUTPUT: ${{ steps.test-action.outputs.status }}
        run: |
          if [[ $TEST_ACTION_OUTPUT != "clean" ]]
          then
            exit 1;
          fi

  test_dirty_failure:
    name: Test Dirty Failure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make dirty
        run: |
          touch `git rev-parse --verify HEAD`

      - uses: CatChen/check-git-status-action@v0.1.4
        id: test-action
        continue-on-error: true

      - name: Verify outputs
        env:
          TEST_ACTION_OUTPUT: ${{ steps.test-action.outputs.status }}
        run: |
          if [[ $TEST_ACTION_OUTPUT != "dirty" ]]
          then
            exit 1;
          fi

  test_dirty_push:
    name: Test Dirty Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Config Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make commit
        run: |
          git checkout -b "test-branch-on-`git rev-parse --verify HEAD`"
          touch `git rev-parse --verify HEAD`
          git add -A
          git commit -am "Test commit for `git rev-parse --verify HEAD`"
          git push -u origin "test-branch-on-`git rev-parse --verify HEAD`"

      - name: Open PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -df -r "github-actions[bot]" -t "Test PR for `git rev-parse --verify HEAD^`" -l "tests"

      - name: Check PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr check --watch

      - name: Close PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr close -d -c "Test finished. Closing PR."
